// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/posts/:slug": {
    params: {
      "slug": string;
    };
  };
  "/api/images/:hash": {
    params: {
      "hash": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/posts/:slug" | "/api/images/:hash";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/post.tsx": {
    id: "routes/post";
    page: "/posts/:slug";
  };
  "routes/images.ts": {
    id: "routes/images";
    page: "/api/images/:hash";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/post": typeof import("./app/routes/post.tsx");
  "routes/images": typeof import("./app/routes/images.ts");
};