name = "example-cloudflare-react-router"
main = "build/server/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./build/client" }

[[r2_buckets]]
binding = "CACHE_BUCKET"
bucket_name = "my-cms-cache"
preview_bucket_name = "my-cms-cache-preview"

# wrangler secret put NOTION_TOKEN
# wrangler secret put NOTION_DATA_SOURCE_ID
